### ISSUE TITLE
'fab deploy' complains about no fabfiles...

### ISSUE THREAD

**Issue by acesuares** [glitchdotcom/WebPutty#37]
I am using Python 2.7 and GAE 1.7.0
on Ubuntu Linux 12.04

**Comment by acesuares** [comment]
Maybe solutution:

``` bash
cd WebPutty
nano fabfile.py
# change:
# APPENGINE_PATH = '/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine'
# to: the real path to your appengine !!!!
# change:
# PYTHON = '/usr/bin/python2.5'
# to: PYTHON = '/usr/bin/python'
# (use 'which python' to find the path to your python)
```

Now, when you do

``` bash
  fab deploy
```

the following error will come up"

```
ImportError: No module named google.appengine.api
```

This is because there is already a google in python:

``` python
>>> import google
>>> google.__file__
'/usr/lib/python2.7/dist-packages/google/__init__.pyc'
```

There should be a better way, but I did this to get rid of the error:

``` bash
sudo rm -rf /usr/lib/python2.7/dist-packages/google
```

**Comment by XULRunner42** [comment]
I had this problem too, I think it's the instructions for installing Google App Engine that are not clear.  The download page instructs you to visit another page for instructions, which links you back to the download page for further details.

No such details are provided anywhere.  I guess they just expect you to know how Python works with packages.

The `google_appengine` folder does not just need to be unzipped, but also put into your Python `system.path` so, on my system, running the unzip command from inside `/usr/lib/python2.7/site-packages/` creates a `google_appengine` folder in there, and the instructions from WebPutty readme work to deploy everything from then on.

I was trying to run pip deploy from inside of `google_appengine/`, obviously a newb mistake.

I do not think you need to `rm -rf /usr/lib/python2.7/dist-packages` anything.

**Comment by acesuares** [comment]
I gave up. Do no harm does not mean anything.
