### ISSUE TITLE
Can we use Python 2.7? (readme.md needs an update?)

### ISSUE THREAD

**Issue by jnchapman** [glitchdotcom/WebPutty#43]
As someone new to Python and GAE can I use Python 2.7 or do you still advise 2.5?
I'm assuming 2.7 will simplify the GAE install a little.

Can this be added to the readme.md

readme.md
"Download and install Python 2.5 and the Google App Engine SDK for Python"

**Comment by dbertram** [comment]
You should be able to use WebPutty with Python 2.7 just fine. @tghw updated the code about 6 months ago to run on 2.7.

I've updated the readme as well. Thanks for bringing this up!
